nelmio_api_doc:
    documentation:
        info:
            title: Distance calculator
            description: Calculates sum of two distances
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    models: { use_jms: false }
